### ISSUE TITLE
feat: implement reverse() method for `linked-list.ts`

### ISSUE THREAD

**Issue by sammaji** [ts-collections/ts-collections#24]
### Describe feature?

 Implement reverse() method for `linked-list.ts`

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mohiwalla** [comment]
Hi @samyabrata-maji, Don't you think the `hacktoberfest-accepted` tag should have been added after a `pull-request` is merged **successfully**? 😅 BTW I've already completed the `TODO`. Would you first assign it to me OR shall I directly make a `PR`?

**Comment by sammaji** [comment]
@mohiwalla you can send a pr.
